name: Create Release

# Create XCFramework when a version is tagged (a tag with prefix "v")
on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Create XCFramework
        uses: mz2/swift-create-xcframework@v1.4.2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Carpaccio.zip,Carpaccio.sha256"
          token: ${{ secrets.GITHUB_TOKEN }}

